"""
This file gathers constants to be called in the computing of CO2 emissions generated by the code.
It is possible to modify them here, but in normal execution shouldn't need to happen too often.
"""

# Current country in which code is being run
COUNTRY_ISO_CODE = "SWE"

# Name of the file in which an emissions report will be generated
OUTPUT_FILE_NAME = "kgCO2eq_emitted_by_code.csv"
