"""
This file gathers constants (written in UPPER_SNAKE_CASE) to be called in the generation of an image output.
It is possible to modify them here, but in normal execution shouldn't need to happen too often.
"""

# Standard notation for an output folder, can be changed if desired.
OUTPUT_STANDARD = "../output"

# Name of the folder in which snapshots will be stored
SNAPSHOT_FOLDER_NAME = "snapshots"

# Image file format is jpg by default. Can be png, but be aware file sizes can get quite large for not much benefit.
IMAGE_FILE_FORMAT = "png"

# Image resolution
DPI = 300

# Argument to be parsed in plt.savefig - wraps size of bounding box around image
BBOX_SETTINGS = "tight"

# Number of frames per second in an assembled video of the screenshots
FRAMES_PER_SECOND = 24

# File format of the video to be generated by assembling images.
VIDEO_FILE_FORMAT = "mp4"

# Codec of the video to be generated by assembling images.
VIDEO_CODEC = "libx264"
